### ISSUE TITLE
DAT201 - Permettre la sauvegarde de fichiers PNG

### ISSUE THREAD

**Issue by plstonge** [calculquebec/magic_clusters#10]
Il manque un package pour permettre la sauvegarde des fichiers PNG:
[https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format)

```pip install vl-convert-python```

Je n'ai pas trouvé ce package dans la wheelhouse. Je ne sais pas si c'est nécessaire. À tester dans le [config.yaml](https://github.com/calculquebec/magic_clusters/blob/common/dat201/config.yaml).

**Comment by ccoulombe** [comment]
Je l'ajoute à la wheelhouse. 

Il faut install `altair[save]` plutôt que le default. Est-ce qu'il faudrait plutôt installé `altair[all]`

https://github.com/vega/altair/blob/78f50e521f3e326490769eb202340d30e073b3cc/pyproject.toml#L60

**Comment by ccoulombe** [comment]
C'est ajouté à la wheelhouse,
